workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    working_directory: menuboss-kr
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      java: 17
      groups:
        - firebase_credentials
        - slack_webhook
      android_signing:
        - KR_TV_DEV
#    scripts:
#      - name: Make Gradle Wrapper Executable
#        script: |
#          chmod +x ./gradlew
#      - name: Create Android Directory and Set SDK Location
#        script: |
#          mkdir -p "$CM_BUILD_DIR/android"
#          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
#      - name: Build Android Debug
#        script: |
#          ./gradlew assembleDebug --info --stacktrace
#    artifacts:
#      - app/build/outputs/**/*.apk
    publishing:
      scripts:
        - name: Publish to Slack
          script: |
            echo "Verifying SLACK_WEBHOOK_URL presence..."
            if [ -z "$SLACK_WEBHOOK_URL" ]; then
              echo "SLACK_WEBHOOK_URL is not set. Exiting..."
            exit 1
            else
              echo "SLACK_WEBHOOK_URL is set. Continuing..."
            fi
    
            BUILD_STATUS="*Build Status*: "
            if [ "$CM_BUILD_STATUS" = "success" ]; then
              BUILD_STATUS_MESSAGE="${BUILD_STATUS} Success :white_check_mark"
            else
              BUILD_STATUS_MESSAGE="${BUILD_STATUS} Fail :x"
            fi
    
            ARTIFACT_URL=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name | endswith(".apk")) | .url')
            
            curl -0 -v -X POST $SLACK_WEBHOOK_URL \
            -H 'Content-type: application/json' \
            --data-raw '
            {
              "text": "안녕하세요! 빌드가 완료되었습니다.",
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "'"$BUILD_STATUS_MESSAGE"'"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Build details: <$CM_BUILD_ID|https://codemagic.io/app/$CM_PROJECT_ID/build/$CM_BUILD_ID>"
                      }
                    },
                    {
                      "type": "section",
                      "block_id": "section567",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Branch:* '"$CM_BRANCH"'"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Android Artifact Link:* [APK 다운로드 링크]('"$ARTIFACT_URL"'|Download)"
                      }
                    },
                  ]
                }
            ]
            }'

#                        "text": "'"$BUILD_STATUS_MESSAGE"': ['"$CM_BUILD_ID"'](https://codemagic.io/app/'"$CM_PROJECT_ID"'/build/'"$CM_BUILD_ID"')"
