workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    working_directory: menuboss-kr
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      java: 17
      groups:
        - firebase_credentials
        - slack_webhook
      android_signing:
        - KR_TV_DEV
    #    scripts:
    #      - name: Make Gradle Wrapper Executable
    #        script: |
    #          chmod +x ./gradlew
    #      - name: Create Android Directory and Set SDK Location
    #        script: |
    #          mkdir -p "$CM_BUILD_DIR/android"
    #          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
    #      - name: Build Android Debug
    #        script: |
    #          ./gradlew assembleDebug --info --stacktrace
    #    artifacts:
    #      - app/build/outputs/**/*.apk
    #    publishing:
    #      slack:
    #        channel: '#C06HB5ASUBS'
    #        notify_on_build_start: true
    #        notify:
    #          success: false
    #          failure: false
    #      firebase:
    #        firebase_service_account: $KR_ANDROID_TV_DEV_FIREBASE_SERVICE_ACCOUNT
    #        android:
    #          app_id: 1:1087980522226:android:64bcfc200958d3f5b21e6b
    #          groups:
    #            - orotcode-team
    #          artifact_type: 'apk'

    publishing:
      scripts:
        - name: Publish to Slack
          script: |
            echo "Verifying SLACK_WEBHOOK_URL presence..."
            if [ -z "$SLACK_WEBHOOK_URL" ]; then
              echo "SLACK_WEBHOOK_URL is not set. Exiting..."
              exit 1
            else
              echo "SLACK_WEBHOOK_URL is set. Continuing..."
            fi
    
            ARTIFACT_URL=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name | endswith(".ipa")) | .url')
    
            curl -X POST $SLACK_WEBHOOK_URL \
            -H 'Content-type: application/json' \
            --data-raw '{
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Build with build id <https://codemagic.io/app/'"$CM_PROJECT_ID"'/build/'"$CM_BUILD_ID"'>"
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "block_id": "section567",
                      "text": {
                        "type": "mrkdwn",
                        "text": "<https://github.com/'"$CM_REPO_SLUG"'> Merge pull request"
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Android Artifact Link* <'"$ARTIFACT_URL"'|Download>"
                      }
                    },
                  ]
                }
            ]
            }'
