workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    working_directory: menuboss-kr
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      groups:
        - firebase_credentials
      android_signing:
        - KR_TV_DEV
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - build/outputs/**/**/*.apk
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:1087980522226:android:3e8715ca1c475ebab21e6b
          groups:
            - orotcode-team
