workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    working_directory: menuboss-kr
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      java: 17
      groups:
        - firebase_credentials
      android_signing:
        - KR_TV_DEV
    scripts:
      - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e # exit on first failed command
          echo $ANDROID_FIREBASE_SECRET > $CM_BUILD_DIR/menuboss-kr/android/app/google-services.json
      - name: Make Gradle Wrapper Executable
        script: |
          chmod +x ./gradlew
      - name: Create Android Directory and Set SDK Location
        script: |
          mkdir -p "$CM_BUILD_DIR/android"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android Debug
        script: |
          ./gradlew assembleDebug --info --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      firebase:
        firebase_service_account: $KR_ANDROID_TV_DEV_FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:1087980522226:android:3e8715ca1c475ebab21e6b
          groups:
            - orotcode-team
