workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    working_directory: menuboss-kr
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      java: 17
      groups:
        - firebase_credentials
        - slack_webhook
      android_signing:
        - KR_TV_DEV
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - name: Build Start Notification to Slack
        script: |
          curl -0 -v -X POST $SLACK_WEBHOOK_URL \
          -H 'Content-type: application/json' \
          --data-raw '
          {
            "text": "Mobile App Build Status",
            "attachments": [
              {
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Mobile App Build Start :rocket:"
                    }
                  },
                  {
                    "type": "section",
                    "block_id": "section567",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Branch: '"$CM_BRANCH"'"
                    }
                  }
                ]
              }
            ]
          }'
      - name: Make Gradle Wrapper Executable
        script: |
          chmod +x ./gradlew
      - name: Create Android Directory and Set SDK Location
        script: |
          mkdir -p "$CM_BUILD_DIR/android"
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android Debug
        script: |
          ./gradlew assembleDebug --info --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      firebase:
        firebase_service_account: $KR_ANDROID_TV_DEV_FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:1087980522226:android:64bcfc200958d3f5b21e6b
          groups:
            - orotcode-team
          artifact_type: 'apk'
      scripts:
        - name: Publish to Slack
          script: |
            BUILD_STATUS="*Status*: "
            BUILD_DETAIL="*Detail*: "
            BUILD_BRANCH="*Branch*: "
            BUILD_ARTIFACT="*Artifact*: "
            
            if [ "$CM_BUILD_STATUS" = "success" ]; then
              BUILD_STATUS_MESSAGE="${BUILD_STATUS} Success :white_check_mark:"
              BUILD_DETAIL_MESSAGE="${BUILD_DETAIL} : <https://codemagic.io/app/$CM_PROJECT_ID/build/$CM_BUILD_ID|View Build>"
              BUILD_BRANCH_MESSAGE="${BUILD_BRANCH} '"$CM_BRANCH"'"
              ARTIFACT_URL=$(echo $CM_ARTIFACT_LINKS | jq -r '.[] | select(.name | endswith(".apk")) | .url')
              BUILD_ARTIFACT_MESSAGE="${BUILD_DETAIL} : <$ARTIFACT_URL|Download">"
            else
              BUILD_STATUS_MESSAGE="${BUILD_STATUS} Fail :x:"
              BUILD_DETAIL_MESSAGE="${BUILD_DETAIL} : <https://codemagic.io/app/$CM_PROJECT_ID/build/$CM_BUILD_ID|View Build>"
              BUILD_BRANCH_MESSAGE="${BUILD_BRANCH} '"$CM_BRANCH"'"
              BUILD_ARTIFACT_MESSAGE="${BUILD_DETAIL} : 사용 가능한 Artifact 파일이 없습니다."
            fi
    
            curl -0 -v -X POST $SLACK_WEBHOOK_URL \
            -H 'Content-type: application/json' \ 
            --data-raw '
            {
              "text": "Mobile App Build Status",
              "attachments": [
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "{$BUILD_STATUS_MESSAGE}"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${BUILD_DETAIL_MESSAGE}"
                      }
                    },
                    {
                      "type": "section",
                      "block_id": "section567",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${BUILD_BRANCH_MESSAGE}"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${BUILD_ARTIFACT_MESSAGE}"
                      }
                    },
                  ]
                }
            ]
            }'